name: PublishNuget

on:
  workflow_dispatch:
    
  release:
    types:
      - published

env:
  SLNX_PATH: 'Source/Portic.slnx'
  DIST_PATH: './dist'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x.x'

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.SLNX_PATH }}

      - name: Build solution
        run: |
          dotnet build ${{ env.SLNX_PATH }} --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test ${{ env.SLNX_PATH }} --configuration Release --no-build

      - name: Pack NuGet packages
        run: |
          dotnet pack Source/Portic/Portic.csproj --configuration Release --no-build -o ${{ env.DIST_PATH }}

          dotnet pack Source/Portic.Middleware.Polly/Portic.Middleware.Polly.csproj --configuration Release --no-build -o ${{ env.DIST_PATH }}

          dotnet pack Source/Portic.Transport.InMemory/Portic.Transport.InMemory.csproj --configuration Release --no-build -o ${{ env.DIST_PATH }}
          dotnet pack Source/Portic.Transport.RabbitMQ/Portic.Transport.RabbitMQ.csproj --configuration Release --no-build -o ${{ env.DIST_PATH }}

      - name: Push to NuGet.org
        run: |
          dotnet nuget push "${{ env.DIST_PATH }}/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate